version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - GITLAB_TOKEN=${GITLAB_TOKEN}
    env_file:
      - .env
    container_name: spring-service
    ports:
      - "8080:8080"
    environment:
      - JWT_SECRET=${JWT_SECRET}
